"""
Provenance Guard — AI Content Attribution API
Flask backend for classifying text as human- or AI-authored.
"""

import os
import re
import json
import math
import uuid
import sqlite3
import statistics
from datetime import datetime, timezone
from functools import wraps

from dotenv import load_dotenv
from flask import Flask, request, jsonify, g
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

# ──────────────────────────────────────────────
# App setup
# ──────────────────────────────────────────────
app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

DB_PATH = os.path.join(os.path.dirname(__file__), "provenance.db")


# ──────────────────────────────────────────────
# Database helpers
# ──────────────────────────────────────────────
def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(exc):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    with sqlite3.connect(DB_PATH) as con:
        con.executescript("""
            CREATE TABLE IF NOT EXISTS classifications (
                content_id   TEXT PRIMARY KEY,
                creator_id   TEXT NOT NULL,
                timestamp    TEXT NOT NULL,
                attribution  TEXT NOT NULL,
                confidence   REAL NOT NULL,
                llm_score    REAL,
                stylo_score  REAL,
                bigram_score REAL,
                label        TEXT NOT NULL,
                status       TEXT NOT NULL DEFAULT 'classified',
                text_snippet TEXT
            );

            CREATE TABLE IF NOT EXISTS appeals (
                appeal_id          TEXT PRIMARY KEY,
                content_id         TEXT NOT NULL,
                creator_id         TEXT,
                timestamp          TEXT NOT NULL,
                creator_reasoning  TEXT NOT NULL,
                FOREIGN KEY (content_id) REFERENCES classifications(content_id)
            );
        """)


init_db()


# ──────────────────────────────────────────────
# Signal 1 — LLM-based classifier (Groq)
# ──────────────────────────────────────────────
def classify_with_llm(text: str) -> float:
    """
    Call Groq (llama-3.3-70b-versatile) to assess AI probability.
    Returns a float in [0.0, 1.0] where 1.0 = highly likely AI-generated.
    Falls back to 0.5 if the API key is missing or call fails.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        # No key: return neutral score so the rest of the system still works
        return 0.5

    try:
        from groq import Groq
        client = Groq(api_key=api_key)

        prompt = f"""You are an expert at detecting AI-generated writing. Analyze the following text and assess the probability that it was generated by an AI language model rather than written by a human.

Consider:
- Sentence uniformity and lack of stylistic variation
- Unnatural smoothness or over-polished phrasing
- Generic transitional phrases ("It is important to note", "Furthermore", "In conclusion")
- Lack of personal voice, idiosyncratic errors, or spontaneous asides
- Overly balanced, hedge-everything tone

Respond ONLY with a JSON object in this exact format (no other text):
{{"ai_probability": 0.85, "reasoning": "brief one-sentence explanation"}}

The text to analyze:
\"\"\"
{text[:3000]}
\"\"\"
"""

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=120,
            temperature=0.1,
        )

        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
        parsed = json.loads(raw)
        score = float(parsed.get("ai_probability", 0.5))
        return max(0.0, min(1.0, score))

    except Exception as exc:
        app.logger.warning(f"LLM signal error: {exc}")
        return 0.5


# ──────────────────────────────────────────────
# Signal 2 — Stylometric heuristics
# ──────────────────────────────────────────────
def _tokenize_sentences(text: str) -> list[str]:
    """Split text into sentences on . ! ? boundaries."""
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s for s in sentences if len(s.split()) >= 2]


def _sentence_length_variance_score(sentences: list[str]) -> float:
    """
    High variance → more human-like → lower AI score.
    Returns 0.0–1.0 where 1.0 = very uniform (AI-like).
    """
    if len(sentences) < 2:
        return 0.5  # not enough data
    lengths = [len(s.split()) for s in sentences]
    std = statistics.stdev(lengths)
    mean = statistics.mean(lengths)
    cv = std / mean if mean > 0 else 0  # coefficient of variation
    # AI text: CV typically < 0.3; human: CV often > 0.5
    # Map: CV=0 → score=1.0; CV=1.0 → score=0.0
    score = max(0.0, 1.0 - (cv / 0.8))
    return round(min(1.0, score), 4)


def _type_token_ratio_score(text: str) -> float:
    """
    Low TTR → repetitive vocab → more AI-like → higher score.
    Returns 0.0–1.0 where 1.0 = very low TTR (AI-like).
    """
    words = re.findall(r"\b[a-z']+\b", text.lower())
    if len(words) < 10:
        return 0.5
    ttr = len(set(words)) / len(words)
    # Typical AI short passage TTR: 0.55–0.70; human: 0.65–0.85
    # Map: TTR=1.0 → score=0.0; TTR=0.4 → score=1.0
    score = max(0.0, 1.0 - ((ttr - 0.4) / 0.5))
    return round(min(1.0, score), 4)


def _punctuation_diversity_score(text: str) -> float:
    """
    Low expressive punctuation density → more AI-like.
    Returns 0.0–1.0 where 1.0 = very low punctuation diversity (AI-like).
    """
    sentences = _tokenize_sentences(text)
    if not sentences:
        return 0.5
    expressive = re.findall(r"[—–\-…;:!?\(\)\[\]\"']", text)
    density = len(expressive) / len(sentences)
    # Human writing: density often > 2 per sentence; AI: < 1
    score = max(0.0, 1.0 - (density / 3.0))
    return round(min(1.0, score), 4)


def classify_with_stylometrics(text: str) -> float:
    """
    Combine three stylometric sub-signals into a single AI probability score.
    Returns 0.0–1.0 where 1.0 = highly likely AI-generated.
    """
    sentences = _tokenize_sentences(text)
    slv = _sentence_length_variance_score(sentences)
    ttr = _type_token_ratio_score(text)
    pds = _punctuation_diversity_score(text)
    # Weighted combination: sentence variance carries most weight
    combined = (0.45 * slv) + (0.35 * ttr) + (0.20 * pds)
    return round(combined, 4)


# ──────────────────────────────────────────────
# Signal 3 (Stretch) — Bigram entropy approximation
# ──────────────────────────────────────────────
def classify_with_bigram_entropy(text: str) -> float:
    """
    Low bigram entropy → predictable word sequences → AI-like.
    Returns 0.0–1.0 where 1.0 = highly likely AI-generated.
    """
    words = re.findall(r"\b[a-z']+\b", text.lower())
    if len(words) < 10:
        return 0.5

    bigrams = [(words[i], words[i + 1]) for i in range(len(words) - 1)]
    total = len(bigrams)
    freq: dict = {}
    for bg in bigrams:
        freq[bg] = freq.get(bg, 0) + 1

    # Shannon entropy of bigram distribution
    entropy = -sum((c / total) * math.log2(c / total) for c in freq.values())
    # Normalize: higher entropy = more random/human-like = lower AI score
    # Typical range: 3–8 bits; scale so 3.0 → score=1.0, 7.0 → score=0.0
    score = max(0.0, 1.0 - ((entropy - 3.0) / 4.5))
    return round(min(1.0, score), 4)


# ──────────────────────────────────────────────
# Confidence scoring (ensemble)
# ──────────────────────────────────────────────
def combine_scores(llm: float, stylo: float, bigram: float) -> float:
    """
    Weighted combination of three signals into a single confidence score.
    LLM: 55%  |  Stylometric: 30%  |  Bigram entropy: 15%
    Returns 0.0–1.0 where 1.0 = highly likely AI-generated.
    """
    combined = (0.55 * llm) + (0.30 * stylo) + (0.15 * bigram)
    return round(combined, 4)


def attribution_from_score(confidence: float) -> str:
    if confidence > 0.70:
        return "likely_ai"
    if confidence < 0.35:
        return "likely_human"
    return "uncertain"


# ──────────────────────────────────────────────
# Transparency label generation
# ──────────────────────────────────────────────
def generate_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)
    human_pct = round((1 - confidence) * 100)

    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content Detected\n"
            f"Our system found strong signals that this content was likely produced by an "
            f"AI writing tool, not written by a human author. Confidence: {pct}%.\n\n"
            f"If you believe this is incorrect, you can submit an appeal — "
            f"we review all contested classifications."
        )
    if attribution == "likely_human":
        return (
            f"✅ Likely Human-Written\n"
            f"Our system found strong signals that this content was written by a human "
            f"author. Confidence in human authorship: {human_pct}%.\n\n"
            f"This label reflects our best assessment — it is not a guarantee. "
            f"Detection systems are imperfect."
        )
    # uncertain
    return (
        f"🔍 Authorship Unclear\n"
        f"Our system couldn't determine with confidence whether this content was "
        f"written by a human or generated by AI. Confidence in AI authorship: {pct}%.\n\n"
        f"We've flagged this for additional context. The creator may choose to appeal "
        f"if they believe the classification is inaccurate."
    )


# ──────────────────────────────────────────────
# Audit log helpers
# ──────────────────────────────────────────────
def log_classification(
    content_id, creator_id, attribution, confidence,
    llm_score, stylo_score, bigram_score, label, text_snippet
):
    db = get_db()
    db.execute(
        """INSERT OR REPLACE INTO classifications
           (content_id, creator_id, timestamp, attribution, confidence,
            llm_score, stylo_score, bigram_score, label, status, text_snippet)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'classified', ?)""",
        (
            content_id, creator_id,
            datetime.now(timezone.utc).isoformat(),
            attribution, confidence,
            llm_score, stylo_score, bigram_score,
            label, text_snippet,
        ),
    )
    db.commit()


def log_appeal(content_id, creator_id, creator_reasoning):
    db = get_db()
    appeal_id = str(uuid.uuid4())
    db.execute(
        """INSERT INTO appeals (appeal_id, content_id, creator_id, timestamp, creator_reasoning)
           VALUES (?, ?, ?, ?, ?)""",
        (appeal_id, content_id, creator_id,
         datetime.now(timezone.utc).isoformat(), creator_reasoning),
    )
    db.execute(
        "UPDATE classifications SET status='under_review' WHERE content_id=?",
        (content_id,),
    )
    db.commit()
    return appeal_id


def get_log_entries(limit: int = 50):
    db = get_db()
    rows = db.execute(
        """SELECT c.*, a.appeal_id, a.creator_reasoning, a.timestamp AS appeal_timestamp
           FROM classifications c
           LEFT JOIN appeals a ON c.content_id = a.content_id
           ORDER BY c.timestamp DESC
           LIMIT ?""",
        (limit,),
    ).fetchall()
    return [dict(r) for r in rows]


def get_analytics():
    db = get_db()
    total = db.execute("SELECT COUNT(*) FROM classifications").fetchone()[0]
    ai_count = db.execute(
        "SELECT COUNT(*) FROM classifications WHERE attribution='likely_ai'"
    ).fetchone()[0]
    human_count = db.execute(
        "SELECT COUNT(*) FROM classifications WHERE attribution='likely_human'"
    ).fetchone()[0]
    uncertain_count = db.execute(
        "SELECT COUNT(*) FROM classifications WHERE attribution='uncertain'"
    ).fetchone()[0]
    appeal_count = db.execute("SELECT COUNT(*) FROM appeals").fetchone()[0]
    avg_confidence = db.execute(
        "SELECT AVG(confidence) FROM classifications"
    ).fetchone()[0]
    under_review = db.execute(
        "SELECT COUNT(*) FROM classifications WHERE status='under_review'"
    ).fetchone()[0]

    return {
        "total_submissions": total,
        "attribution_breakdown": {
            "likely_ai": ai_count,
            "likely_human": human_count,
            "uncertain": uncertain_count,
        },
        "appeal_count": appeal_count,
        "appeal_rate": round(appeal_count / total, 4) if total else 0,
        "under_review": under_review,
        "average_confidence": round(avg_confidence, 4) if avg_confidence else None,
    }


# ──────────────────────────────────────────────
# Routes
# ──────────────────────────────────────────────
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    POST /submit
    Body: {"text": "...", "creator_id": "..."}
    Returns: classification result with confidence score and transparency label.
    """
    data = request.get_json(silent=True) or {}
    text = (data.get("text") or "").strip()
    creator_id = (data.get("creator_id") or "anonymous").strip()

    if not text:
        return jsonify({"error": "text field is required and must not be empty"}), 400
    if len(text) < 20:
        return jsonify({"error": "text is too short for meaningful analysis (min 20 chars)"}), 400

    content_id = str(uuid.uuid4())

    # Run detection pipeline
    llm_score    = classify_with_llm(text)
    stylo_score  = classify_with_stylometrics(text)
    bigram_score = classify_with_bigram_entropy(text)
    confidence   = combine_scores(llm_score, stylo_score, bigram_score)
    attribution  = attribution_from_score(confidence)
    label        = generate_label(attribution, confidence)

    # Persist to audit log
    snippet = text[:200] + ("…" if len(text) > 200 else "")
    log_classification(
        content_id, creator_id, attribution, confidence,
        llm_score, stylo_score, bigram_score, label, snippet
    )

    return jsonify({
        "content_id":   content_id,
        "creator_id":   creator_id,
        "attribution":  attribution,
        "confidence":   confidence,
        "signals": {
            "llm_score":    llm_score,
            "stylo_score":  stylo_score,
            "bigram_score": bigram_score,
        },
        "label":        label,
        "status":       "classified",
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    POST /appeal
    Body: {"content_id": "...", "creator_reasoning": "..."}
    Updates status to under_review and logs the appeal.
    """
    data = request.get_json(silent=True) or {}
    content_id        = (data.get("content_id") or "").strip()
    creator_reasoning = (data.get("creator_reasoning") or "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if not creator_reasoning:
        return jsonify({"error": "creator_reasoning is required"}), 400

    db = get_db()
    row = db.execute(
        "SELECT * FROM classifications WHERE content_id=?", (content_id,)
    ).fetchone()

    if not row:
        return jsonify({"error": f"No classification found for content_id: {content_id}"}), 404

    appeal_id = log_appeal(content_id, row["creator_id"], creator_reasoning)

    return jsonify({
        "appeal_id":        appeal_id,
        "content_id":       content_id,
        "status":           "under_review",
        "message":          "Your appeal has been received and logged. A human reviewer will assess your classification.",
        "original_verdict": {
            "attribution": row["attribution"],
            "confidence":  row["confidence"],
            "timestamp":   row["timestamp"],
        },
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    """
    GET /log?limit=N
    Returns the most recent audit log entries.
    """
    limit = min(int(request.args.get("limit", 20)), 200)
    entries = get_log_entries(limit)
    return jsonify({"count": len(entries), "entries": entries}), 200


@app.route("/analytics", methods=["GET"])
def analytics():
    """
    GET /analytics  (Stretch feature)
    Returns detection pattern summary, appeal rate, and score distribution stats.
    """
    data = get_analytics()
    return jsonify(data), 200


@app.route("/", methods=["GET"])
def index():
    return jsonify({
        "service": "Provenance Guard",
        "status": "ok",
        "endpoints": {
            "POST /submit": "Submit text for classification",
            "POST /appeal": "Contest a classification",
            "GET /log": "View audit log",
            "GET /analytics": "View detection stats",
            "GET /health": "Health check"
        }
    }), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "provenance-guard"}), 200


# ──────────────────────────────────────────────
# Rate limit error handler
# ──────────────────────────────────────────────
@app.errorhandler(429)
def rate_limit_hit(e):
    return jsonify({
        "error": "Rate limit exceeded",
        "message": "Too many submissions. Limit: 10 per minute, 100 per day.",
        "retry_after": str(e.description),
    }), 429


if __name__ == "__main__":
    app.run(debug=True, port=8080)